# Generated by Django 4.0.4 on 2022-06-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
