# Generated by Django 4.0.4 on 2022-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_user_alter_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registereduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
