# Generated by Django 4.0.4 on 2022-06-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_document_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='username',
        ),
    ]
