# Generated by Django 4.0.4 on 2022-06-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_user_document_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_title', models.CharField(max_length=300)),
                ('audio_file', models.FileField(upload_to='')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.user')),
            ],
        ),
    ]
