# Generated by Django 4.0.4 on 2022-06-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='username',
            field=models.CharField(default='user', max_length=500),
        ),
    ]
